In [13]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore")

In [14]:
df=pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [15]:
df["bedrooms"]=df["bedrooms"].fillna(df["bedrooms"].median())

In [16]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [17]:
x_df=df.drop(["price"],axis=1)
x_df

area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8

In [18]:
y_df=df["price"]
y_df

0    550000
1    565000
2    610000
3    595000
4    760000
5    810000
Name: price, dtype: int64

In [19]:
lr=LinearRegression()
lr.fit(x_df,y_df)

LinearRegression()

In [20]:
lr.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [21]:
lr.intercept_

221323.00186540408

In [24]:
y=112.06244194*area +23388.88007794*bedrooms -3231.71790863*age +221323.00186540408

NameError: name 'area' is not defined

In [25]:
# Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old
lr.predict([[3000,3,40]])

array([498408.25158031])

In [26]:
112.06244194*3000+23388.88007794*3-3231.71790863*40+221323.00186540408

498408.2515740241

**Find price of home with 2500 sqr ft area, 4 bedrooms,  5 year old**

In [27]:
lr.predict([[2500,4,5]])

array([578876.03748933])