In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv("homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
x_df=df.drop(["price"],axis=1)
x_df

area
0  2600
1  3000
2  3200
3  3600
4  4000

In [4]:
y_df=df["price"]
y_df

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

In [5]:
lr=LinearRegression()
lr.fit(x_df,y_df)

LinearRegression()

In [6]:
lr.coef_

array([135.78767123])

In [7]:
lr.intercept_

180616.43835616432

###PICKLE FILE

In [8]:
import pickle

In [9]:
with open("lr_model","wb") as file:
    pickle.dump(lr,file)

In [11]:
with open("lr_model","rb") as file:
    mp=pickle.load(file)

In [12]:
mp.coef_

array([135.78767123])

In [13]:
mp.intercept_

180616.43835616432

In [14]:
#create a file named sample.json with some data
import json
sampleJson={
    "name":"Dhoni",
    "Number":"7",
    "Age":"40"
} 
json_object=json.dumps(sampleJson)

In [15]:
with open("sample.json","w") as file:
    file.write(json_object)


In [17]:
with open("sample.json","rb") as file:
    new_data=json.load(file)


In [18]:
new_data

{'name': 'Dhoni', 'Number': '7', 'Age': '40'}

In [19]:
import joblib

In [20]:
joblib.dump(lr,"model_joblib_new")

['model_joblib_new']

In [21]:
mj=joblib.load("model_joblib_new")

In [22]:
mj.coef_

array([135.78767123])

In [23]:
mj.intercept_

180616.43835616432

In [24]:
joblib.load("lr_model")

LinearRegression()