In [1]:
#install python package-Numpy

In [2]:
#install python package-Numpy
#pip install numpy

In [3]:
import numpy as np

In [4]:
myList=[1, 2, 3, 4, 5]

In [5]:
print(myList)

[1, 2, 3, 4, 5]


In [6]:
type(myList)

list

In [7]:
#dir(np)

In [8]:
#help(np)

In [9]:
arr=np.array(myList)

In [10]:
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
#shape of the array
arr.shape

(5,)

In [12]:
arr.size

5

In [13]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]
arr=np.array([my_lst1,my_lst2,my_lst3])

In [14]:
type(arr)

numpy.ndarray

In [15]:
arr.shape

(3, 5)

In [16]:
arr.size

15

In [17]:
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [18]:
#numpy array indexing
#get the first element of the array
my_list1=[1,2,3,4,5]
arr=np.array(my_list1)

In [19]:
print(arr)

[1 2 3 4 5]


In [20]:
print(arr[0])

1


In [21]:
#get the second element
print(arr[1])

2


In [22]:
#get the third and fourth element from the array and add them
print("The third element of array is:",arr[2])
print("The fourth element of array is:",arr[3])

The third element of array is: 3
The fourth element of array is: 4


In [23]:
#access 2D array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]
arr=np.array([my_lst1,my_lst2,my_lst3])

In [24]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [25]:
arr[0,1]

2

In [26]:
arr[1,4]

6

In [27]:
 #Create a 2D array
valArr = np.array([[1,2,3],[4,5,6]])
print("Printing The Variable value:",valArr)
print("\n")
print("Printing the size:",valArr.shape)
print("\n")
print("Printing the shape:",valArr.size)
print("\n")
print("Printing the first row first element:",valArr[0,0])
print("\n")
print("printing the second row second element:",valArr[1,2])

Printing The Variable value: [[1 2 3]
 [4 5 6]]


Printing the size: (2, 3)


Printing the shape: 6


Printing the first row first element: 1


printing the second row second element: 6


In [28]:
newArr= np.array([[1,2,3,4,5],[6,7,8,9,10],[1,2,3,4,5],[11,12,13,14,15],[20,25,30,35,40]])
print("Printing The Variable value:",newArr)
print("\n")
print("Printing the size:",newArr.shape)
print("\n")
print("Printing the shape:",newArr.size)
print("\n")
print("Printing the first row fifth element:",newArr[0,4])
print("\n")
print("printing the fifth row third element:",newArr[4,2])
print("\n")
print("printing the third row fourth element:",newArr[2,3])

Printing The Variable value: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [11 12 13 14 15]
 [20 25 30 35 40]]


Printing the size: (5, 5)


Printing the shape: 25


Printing the first row fifth element: 5


printing the fifth row third element: 30


printing the third row fourth element: 4


In [29]:
#Negative indexing
valArr = np.array([[1,2,3],[4,5,6]])
print(valArr)
valArr[1,-2]
valArr[0,-1]

[[1 2 3]
 [4 5 6]]


3

In [30]:
#Numpy Array Slicing
valArr=[1,2,3,4,5,6,7,8,9,10]
print(valArr)
#arr[start:end]
valArr[3:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


[4, 5, 6, 7, 8, 9, 10]

In [32]:
valArr=[1,2,3,4,5,6,7,8,9,10]
#print(valArr)
valArr[:5]

[1, 2, 3, 4, 5]

In [37]:
valArr=[1,2,3,4,5,6,7,8,9,10]
valArr[-3:-1]

[8, 9]

In [44]:
valArr=[1,2,3,4,5,6,7,8,9,10,11]
valArr[0:8:2]
valArr[::2]   #known as step function
valArr[1::2]

[2, 4, 6, 8, 10]

In [45]:
valArr[1::3]

[2, 5, 8, 11]

In [46]:
#Slicing 2D Arrays
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]
arr=np.array([my_lst1,my_lst2,my_lst3])
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [47]:
arr[1:,:]

array([[2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [48]:
arr[0:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [52]:
arr[2:,:]

array([[9, 7, 6, 8, 9]])

In [56]:
arr[0:2,2:]

array([[3, 4, 5],
       [4, 5, 6]])

In [62]:
#Arange function
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [63]:
#Linspace
np.linspace(0,100)  #follows the normal distribution curve

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])